apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-tls
  namespace: cert-manager
spec:
  secretName: myapp-tls-secret
  commonName: myapp.local  # Replace with your domain or IP
  dnsNames:
    - myapp.local          # Replace with your domain or IP
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
